global:
  scrape_interval: 5s  # Frecuencia de recolección de métricas

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 'node-exporter:9100'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'cadvisor:8080'
