name: CI/CD - Auto Merge Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  test-and-merge:
    runs-on: ubuntu-latest
    container: 
      image: docker:20.10.21-dind
    
    services:
      docker:
        image: docker:20.10.21-dind
        options: --privileged

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        
      - name: Instalar Docker Compose
        run: |
          apk add --no-cache docker-compose git curl
          
      - name: Preparar archivo de configuración para Prometheus
        run: |
          mkdir -p temp_prometheus
          cp prometheus.yml temp_prometheus/
          
      - name: Modificar docker-compose temporalmente para CI/CD
        run: |
          sed -i 's|./prometheus.yml:/etc/prometheus/prometheus.yml|./temp_prometheus:/etc/prometheus|g' docker-compose.yml
          cat docker-compose.yml
          
      - name: Construir y levantar contenedores con Docker Compose
        run: |
          docker-compose up --build -d
          sleep 10  # Espera para que los contenedores se levanten
          docker ps  # Verifica que los contenedores están corriendo correctamente

      - name: Confirm success
        if: success()
        run: echo "Todo salió bien ✅ Los contenedores se levantaron correctamente, se creará un pull request"

      - name: Crear Pull Request desde dev hacia main
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GA_REDDIT }}" \
          -d '{
                "title": "Automated PR from dev to main",
                "head": "dev",
                "base": "main",
                "body": "This is an automated pull request to merge dev into main."
              }' \
          https://api.github.com/repos/${{ github.repository }}/pulls
        env:
          GITHUB_TOKEN: ${{ secrets.GA_REDDIT }}